### PR TITLE
Do not attempt to rehash in a system-wide install

### PR DESCRIPTION
**Pull request by whatcould**
Prevents an `cannot rehash:` error on each login with a pyenv_system_install install

### Description

With a system-wide install, any user login results in the error, `pyenv: cannot rehash: /usr/local/pyenv/shims isn't writable`

Pyenv suggests disabling rehash in this case, see: https://github.com/pyenv/pyenv/issues/1157#issuecomment-418446159

### Issues Resolved

[List any existing issues this PR resolves]

### Contribution Check List

- [ ] All tests pass.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [ ] Changes have been added to `CHANGELOG.md`

### CODE REVIEW

**Comment by darwin67** [comment]
@whatcould hey. thanks for submitting the patch.
appologies for the CI since Circle has been pretty much useless for this project.

the patch itself is pretty simple so I'll just validate the tests locally before approving.
sorry for the inconvenience.

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This Pull Request is probably missing tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by darwin67** [comment]
> 	1 Error
> no_entry_sign 	Please include a CHANGELOG entry.
> 	1 Warning
> warning 	This Pull Request is probably missing tests.
> 
> Generated by no_entry_sign [Danger](https://danger.systems/)

@whatcould could you resolve these and rebase on master?
please add tests to verify your change as well.

**Comment by Xorima** [comment]
Hey @whatcould 

This is a really good change but I need to insist on tests before it goes into the codebase, just so that we don't break it again in future 👍 

If you need help drop by the #sous-chefs channel in https://community-slack.chef.io/

Danger is expected to fail and is something I will be working on shortly

**Comment by Xorima** [comment]
Hey @whatcould 

Do you have time to work on the tests?

thanks

Sous Chefs

**Comment by whatcould** [comment]
@Xorima I'll look at them!

**Comment by damacus** [comment]
hey @whatcould have you had time to look a these yet we'd love this in!

**Comment by MarkGibbons** [comment]
#73 incorporates this fix.  Closing this PR in favor of #73.

**Pull request closed without merging**
