### PR TITLE
Add umask support to pip resource

### PR DESCRIPTION
**Pull request by frank-m**
# Description

Adds umask support to pip resource to allow pip to work properly on systems which have a very restrictive umask (like 0077) set.

## Issues Resolved

-

## Check List

- [x] All tests pass. See TESTING.md for details.
- [ ] New functionality includes testing.  - I don't see how I should test this as the default umask in the test systems is already fine.
- [x] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This Pull Request is probably missing tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by damacus** [comment]
Hey @frank-m can you run the kitchen tests locally and paste the output. Right now this is failing on Chef 17 compatibility, but there's no reason this shouldn't be merged as is.

**Comment by damacus** [comment]
After we've done that, would you mind fixing the deprecation in another PR?

**Review by Xorima — DISMISSED** [review]

**Comment by frank-m** [comment]
@damacus The tests are currently broken it seems. Even locally with chef 16 it assumes a lot of old information. Would it be possible to merge this one? Not sure if we can override the job status.

I am leaving tomorrow for three weeks holiday so I won't have time now to fix the tests and the unified mode. I can do it when I get back however.

**Comment by damacus** [comment]
Usually, I'd be pretty against just merging this in. But we're adding new properties here, rather than removing them 👍🏼

**Comment by kitchen-porter** [comment]
Released as: [3.5.0](https://github.com/sous-chefs/pyenv/releases/tag/3.5.0)

**Pull request merged**
